[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
mantle_sepolia = "https://rpc.sepolia.mantle.xyz"

[etherscan]
mantle_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.mantlescan.xyz/api" }
